### ISSUE TITLE
bootstrap progetto

### ISSUE THREAD

**Issue by moebiusmania** [edgemony-coding-bootcamp/project-salvatore-a#1]
identificare e selezionare le tecnologie e librerie da usare

- quale soluzione di hosting usare
- quale tipo di backend (farlocco) usare
- framework CSS?
- eventuali pacchetti NPM utili

**Comment by Gcollova** [comment]
Hosting:Firebase
BackEnd:Firebase
framework CSS: SASS
npm packages: redux, react-redux, redux-thunk, node-sass, react-router
