### ISSUE TITLE
definire la struttura dei dati

### ISSUE THREAD

**Issue by moebiusmania** [edgemony-coding-bootcamp/project-salvatore-a#2]
* quali endpoint ci servono?
* come saranno strutturati i dati nei vari endpoint?

**Comment by Tutanto** [comment]
**Struttura dei dati**

Abbiamo scelto di creare **2** diverse collezioni di dati: Users e Messages

Esempio di singolo Users:

{
    "id": 1,
    "username": "Bret",
    "name": "Bret",
    "lastname": "Pippus",
    "email": "Sincere@april.biz",
    "photo": "url",
    "logged": false
}

Esempio di Messages:

{
    "messageId": 1,
    "Userid": 1,
    "date": "08-02-2022",
    "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
}
