### ISSUE TITLE
navigazione router-based

### ISSUE THREAD

**Issue by moebiusmania** [edgemony-coding-bootcamp/project-salvatore-a#33]
se clicco su una coversazione

- aggiono l'url dell'applicazione
- carico i dati della conversazione
- li renderizzo in pagina

**Comment by Tutanto** [comment]
Issue portata avanti nel branch "feature/navigazione_router_base"
Riusciamo ad aggiornare l'URL e a renderizzare la corretta conversazione, ma non riusciamo a usare l'URL per arrivare direttamente alla conversazione.
